@startuml
set namespaceSeparator ::

class "flutter::lib::src::material::chip_input.dart::InputChip" {
  +dynamic avatar
  +dynamic label
  +dynamic labelStyle
  +dynamic labelPadding
  +bool selected
  +bool isEnabled
  +dynamic onSelected
  +dynamic deleteIcon
  +dynamic onDeleted
  +dynamic deleteIconColor
  +String? deleteButtonTooltipMessage
  +dynamic onPressed
  +double? pressElevation
  +dynamic disabledColor
  +dynamic selectedColor
  +String? tooltip
  +dynamic side
  +dynamic shape
  +dynamic clipBehavior
  +dynamic focusNode
  +bool autofocus
  +dynamic backgroundColor
  +dynamic padding
  +VisualDensity? visualDensity
  +MaterialTapTargetSize? materialTapTargetSize
  +double? elevation
  +dynamic shadowColor
  +dynamic surfaceTintColor
  +dynamic selectedShadowColor
  +bool? showCheckmark
  +dynamic checkmarkColor
  +dynamic avatarBorder
  +dynamic iconTheme
  +bool useDeleteButtonTooltip
  +dynamic build()
}

"flutter::lib::src::material::chip_input.dart::InputChip" o-- "flutter::lib::src::material::theme_data.dart::VisualDensity"
"flutter::lib::src::material::chip_input.dart::InputChip" o-- "flutter::lib::src::material::theme_data.dart::MaterialTapTargetSize"
"flutter::lib::src::material::chip.dart::ChipAttributes" <|-- "flutter::lib::src::material::chip_input.dart::InputChip"
"flutter::lib::src::material::chip.dart::DeletableChipAttributes" <|-- "flutter::lib::src::material::chip_input.dart::InputChip"
"flutter::lib::src::material::chip.dart::SelectableChipAttributes" <|-- "flutter::lib::src::material::chip_input.dart::InputChip"
"flutter::lib::src::material::chip.dart::CheckmarkableChipAttributes" <|-- "flutter::lib::src::material::chip_input.dart::InputChip"
"flutter::lib::src::material::chip.dart::DisabledChipAttributes" <|-- "flutter::lib::src::material::chip_input.dart::InputChip"
"flutter::lib::src::material::chip.dart::TappableChipAttributes" <|-- "flutter::lib::src::material::chip_input.dart::InputChip"

class "flutter::lib::src::material::chip_input.dart::_InputChipDefaultsM3" {
  +dynamic context
  +bool isEnabled
  +dynamic labelStyle
  +dynamic backgroundColor
  +dynamic shadowColor
  +dynamic surfaceTintColor
  +dynamic selectedColor
  +dynamic checkmarkColor
  +dynamic disabledColor
  +dynamic deleteIconColor
  +dynamic side
  +dynamic iconTheme
  +dynamic padding
  +dynamic labelPadding
}

"flutter::lib::src::material::chip_theme.dart::ChipThemeData" <|-- "flutter::lib::src::material::chip_input.dart::_InputChipDefaultsM3"


@enduml