@startuml
set namespaceSeparator ::

class "flutter::lib::src::material::elevated_button.dart::ElevatedButton" {
  {static} +ButtonStyle styleFrom()
  +ButtonStyle defaultStyleOf()
  +ButtonStyle? themeStyleOf()
}

"flutter::lib::src::material::button_style_button.dart::ButtonStyleButton" <|-- "flutter::lib::src::material::elevated_button.dart::ElevatedButton"

class "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultColor" {
  +dynamic color
  +dynamic disabled
  +dynamic resolve()
}

"flutter::lib::src::material::material_state.dart::MaterialStateProperty" <|-- "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultColor"

class "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultOverlay" {
  +dynamic overlay
  +dynamic resolve()
}

"flutter::lib::src::material::material_state.dart::MaterialStateProperty" <|-- "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultOverlay"

class "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultElevation" {
  +double elevation
  +double resolve()
}

"flutter::lib::src::material::material_state.dart::MaterialStateProperty" <|-- "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultElevation"

class "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultMouseCursor" {
  +dynamic enabledCursor
  +dynamic disabledCursor
  +dynamic resolve()
}

"flutter::lib::src::material::material_state.dart::MaterialStateProperty" <|-- "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultMouseCursor"

class "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonWithIcon" {
  +ButtonStyle defaultStyleOf()
}

"flutter::lib::src::material::elevated_button.dart::ElevatedButton" <|-- "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonWithIcon"

class "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonWithIconChild" {
  +dynamic label
  +dynamic icon
  +dynamic build()
}

class "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultsM3" {
  +dynamic context
  -ColorScheme _colors
  +MaterialStateProperty<dynamic> textStyle
  +MaterialStateProperty<dynamic>? backgroundColor
  +MaterialStateProperty<dynamic>? foregroundColor
  +MaterialStateProperty<dynamic>? overlayColor
  +MaterialStateProperty<dynamic>? shadowColor
  +MaterialStateProperty<dynamic>? surfaceTintColor
  +MaterialStateProperty<double>? elevation
  +MaterialStateProperty<dynamic>? padding
  +MaterialStateProperty<dynamic>? minimumSize
  +MaterialStateProperty<dynamic>? maximumSize
  +MaterialStateProperty<dynamic>? shape
  +MaterialStateProperty<dynamic>? mouseCursor
  +VisualDensity? visualDensity
  +MaterialTapTargetSize? tapTargetSize
  +InteractiveInkFeatureFactory? splashFactory
}

"flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultsM3" o-- "flutter::lib::src::material::color_scheme.dart::ColorScheme"
"flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultsM3" o-- "flutter::lib::src::material::material_state.dart::MaterialStateProperty<dynamic>"
"flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultsM3" o-- "flutter::lib::src::material::material_state.dart::MaterialStateProperty<double>"
"flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultsM3" o-- "flutter::lib::src::material::theme_data.dart::VisualDensity"
"flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultsM3" o-- "flutter::lib::src::material::theme_data.dart::MaterialTapTargetSize"
"flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultsM3" o-- "flutter::lib::src::material::ink_well.dart::InteractiveInkFeatureFactory"
"flutter::lib::src::material::button_style.dart::ButtonStyle" <|-- "flutter::lib::src::material::elevated_button.dart::_ElevatedButtonDefaultsM3"


@enduml