@startuml
set namespaceSeparator ::

abstract class "flutter::lib::src::material::material_localizations.dart::MaterialLocalizations" {
  +String openAppDrawerTooltip
  +String backButtonTooltip
  +String closeButtonTooltip
  +String deleteButtonTooltip
  +String moreButtonTooltip
  +String nextMonthTooltip
  +String previousMonthTooltip
  +String firstPageTooltip
  +String lastPageTooltip
  +String nextPageTooltip
  +String previousPageTooltip
  +String showMenuTooltip
  +String licensesPageTitle
  +String rowsPerPageTitle
  +String cancelButtonLabel
  +String closeButtonLabel
  +String continueButtonLabel
  +String copyButtonLabel
  +String cutButtonLabel
  +String okButtonLabel
  +String pasteButtonLabel
  +String selectAllButtonLabel
  +String viewLicensesButtonLabel
  +String anteMeridiemAbbreviation
  +String postMeridiemAbbreviation
  +String timePickerHourModeAnnouncement
  +String timePickerMinuteModeAnnouncement
  +String modalBarrierDismissLabel
  +String drawerLabel
  +String popupMenuLabel
  +String menuBarMenuLabel
  +String dialogLabel
  +String alertDialogLabel
  +String searchFieldLabel
  +ScriptCategory scriptCategory
  +List<String> narrowWeekdays
  +int firstDayOfWeekIndex
  +String dateSeparator
  +String dateHelpText
  +String selectYearSemanticsLabel
  +String unspecifiedDate
  +String unspecifiedDateRange
  +String dateInputLabel
  +String dateRangeStartLabel
  +String dateRangeEndLabel
  +String invalidDateFormatLabel
  +String invalidDateRangeLabel
  +String dateOutOfRangeLabel
  +String saveButtonLabel
  +String datePickerHelpText
  +String dateRangePickerHelpText
  +String calendarModeButtonLabel
  +String inputDateModeButtonLabel
  +String timePickerDialHelpText
  +String timePickerInputHelpText
  +String timePickerHourLabel
  +String timePickerMinuteLabel
  +String invalidTimeLabel
  +String dialModeButtonLabel
  +String inputTimeModeButtonLabel
  +String signedInLabel
  +String hideAccountsLabel
  +String showAccountsLabel
  +String reorderItemToStart
  +String reorderItemToEnd
  +String reorderItemUp
  +String reorderItemDown
  +String reorderItemLeft
  +String reorderItemRight
  +String expandedIconTapHint
  +String collapsedIconTapHint
  +String refreshIndicatorSemanticLabel
  +String keyboardKeyAlt
  +String keyboardKeyAltGraph
  +String keyboardKeyBackspace
  +String keyboardKeyCapsLock
  +String keyboardKeyChannelDown
  +String keyboardKeyChannelUp
  +String keyboardKeyControl
  +String keyboardKeyDelete
  +String keyboardKeyEject
  +String keyboardKeyEnd
  +String keyboardKeyEscape
  +String keyboardKeyFn
  +String keyboardKeyHome
  +String keyboardKeyInsert
  +String keyboardKeyMeta
  +String keyboardKeyMetaMacOs
  +String keyboardKeyMetaWindows
  +String keyboardKeyNumLock
  +String keyboardKeyNumpad1
  +String keyboardKeyNumpad2
  +String keyboardKeyNumpad3
  +String keyboardKeyNumpad4
  +String keyboardKeyNumpad5
  +String keyboardKeyNumpad6
  +String keyboardKeyNumpad7
  +String keyboardKeyNumpad8
  +String keyboardKeyNumpad9
  +String keyboardKeyNumpad0
  +String keyboardKeyNumpadAdd
  +String keyboardKeyNumpadComma
  +String keyboardKeyNumpadDecimal
  +String keyboardKeyNumpadDivide
  +String keyboardKeyNumpadEnter
  +String keyboardKeyNumpadEqual
  +String keyboardKeyNumpadMultiply
  +String keyboardKeyNumpadParenLeft
  +String keyboardKeyNumpadParenRight
  +String keyboardKeyNumpadSubtract
  +String keyboardKeyPageDown
  +String keyboardKeyPageUp
  +String keyboardKeyPower
  +String keyboardKeyPowerOff
  +String keyboardKeyPrintScreen
  +String keyboardKeyScrollLock
  +String keyboardKeySelect
  +String keyboardKeySpace
  +String aboutListTileTitle()
  +String licensesPackageDetailText()
  +String pageRowsInfoTitle()
  +String tabLabel()
  +String selectedRowCountTitle()
  +TimeOfDayFormat timeOfDayFormat()
  +String formatDecimal()
  +String formatHour()
  +String formatMinute()
  +String formatTimeOfDay()
  +String formatYear()
  +String formatCompactDate()
  +String formatShortDate()
  +String formatMediumDate()
  +String formatFullDate()
  +String formatMonthYear()
  +String formatShortMonthDay()
  +DateTime? parseCompactDate()
  +String dateRangeStartDateSemanticLabel()
  +String dateRangeEndDateSemanticLabel()
  +String remainingTextFieldCharacterCount()
  {static} +MaterialLocalizations of()
}

"flutter::lib::src::material::material_localizations.dart::MaterialLocalizations" o-- "flutter::lib::src::material::typography.dart::ScriptCategory"

class "flutter::lib::src::material::material_localizations.dart::_MaterialLocalizationsDelegate" {
  +bool isSupported()
  +Future<MaterialLocalizations> load()
  +bool shouldReload()
  +String toString()
}

class "flutter::lib::src::material::material_localizations.dart::DefaultMaterialLocalizations" {
  {static} -List<String> _shortWeekdays
  {static} -List<String> _weekdays
  {static} -List<String> _narrowWeekdays
  {static} -List<String> _shortMonths
  {static} -List<String> _months
  {static} +dynamic delegate
  +List<String> narrowWeekdays
  +int firstDayOfWeekIndex
  +String dateSeparator
  +String dateHelpText
  +String selectYearSemanticsLabel
  +String unspecifiedDate
  +String unspecifiedDateRange
  +String dateInputLabel
  +String dateRangeStartLabel
  +String dateRangeEndLabel
  +String invalidDateFormatLabel
  +String invalidDateRangeLabel
  +String dateOutOfRangeLabel
  +String saveButtonLabel
  +String datePickerHelpText
  +String dateRangePickerHelpText
  +String calendarModeButtonLabel
  +String inputDateModeButtonLabel
  +String timePickerDialHelpText
  +String timePickerInputHelpText
  +String timePickerHourLabel
  +String timePickerMinuteLabel
  +String invalidTimeLabel
  +String dialModeButtonLabel
  +String inputTimeModeButtonLabel
  +String openAppDrawerTooltip
  +String backButtonTooltip
  +String closeButtonTooltip
  +String deleteButtonTooltip
  +String moreButtonTooltip
  +String nextMonthTooltip
  +String previousMonthTooltip
  +String nextPageTooltip
  +String previousPageTooltip
  +String firstPageTooltip
  +String lastPageTooltip
  +String showMenuTooltip
  +String drawerLabel
  +String menuBarMenuLabel
  +String popupMenuLabel
  +String dialogLabel
  +String alertDialogLabel
  +String searchFieldLabel
  +String licensesPageTitle
  +String rowsPerPageTitle
  +String cancelButtonLabel
  +String closeButtonLabel
  +String continueButtonLabel
  +String copyButtonLabel
  +String cutButtonLabel
  +String okButtonLabel
  +String pasteButtonLabel
  +String selectAllButtonLabel
  +String viewLicensesButtonLabel
  +String anteMeridiemAbbreviation
  +String postMeridiemAbbreviation
  +String timePickerHourModeAnnouncement
  +String timePickerMinuteModeAnnouncement
  +String modalBarrierDismissLabel
  +ScriptCategory scriptCategory
  +String signedInLabel
  +String hideAccountsLabel
  +String showAccountsLabel
  +String reorderItemUp
  +String reorderItemDown
  +String reorderItemLeft
  +String reorderItemRight
  +String reorderItemToEnd
  +String reorderItemToStart
  +String expandedIconTapHint
  +String collapsedIconTapHint
  +String refreshIndicatorSemanticLabel
  +String keyboardKeyAlt
  +String keyboardKeyAltGraph
  +String keyboardKeyBackspace
  +String keyboardKeyCapsLock
  +String keyboardKeyChannelDown
  +String keyboardKeyChannelUp
  +String keyboardKeyControl
  +String keyboardKeyDelete
  +String keyboardKeyEject
  +String keyboardKeyEnd
  +String keyboardKeyEscape
  +String keyboardKeyFn
  +String keyboardKeyHome
  +String keyboardKeyInsert
  +String keyboardKeyMeta
  +String keyboardKeyMetaMacOs
  +String keyboardKeyMetaWindows
  +String keyboardKeyNumLock
  +String keyboardKeyNumpad1
  +String keyboardKeyNumpad2
  +String keyboardKeyNumpad3
  +String keyboardKeyNumpad4
  +String keyboardKeyNumpad5
  +String keyboardKeyNumpad6
  +String keyboardKeyNumpad7
  +String keyboardKeyNumpad8
  +String keyboardKeyNumpad9
  +String keyboardKeyNumpad0
  +String keyboardKeyNumpadAdd
  +String keyboardKeyNumpadComma
  +String keyboardKeyNumpadDecimal
  +String keyboardKeyNumpadDivide
  +String keyboardKeyNumpadEnter
  +String keyboardKeyNumpadEqual
  +String keyboardKeyNumpadMultiply
  +String keyboardKeyNumpadParenLeft
  +String keyboardKeyNumpadParenRight
  +String keyboardKeyNumpadSubtract
  +String keyboardKeyPageDown
  +String keyboardKeyPageUp
  +String keyboardKeyPower
  +String keyboardKeyPowerOff
  +String keyboardKeyPrintScreen
  +String keyboardKeyScrollLock
  +String keyboardKeySelect
  +String keyboardKeySpace
  -int _getDaysInMonth()
  +String formatHour()
  -String _formatTwoDigitZeroPad()
  +String formatMinute()
  +String formatYear()
  +String formatCompactDate()
  +String formatShortDate()
  +String formatMediumDate()
  +String formatFullDate()
  +String formatMonthYear()
  +String formatShortMonthDay()
  +DateTime? parseCompactDate()
  +String dateRangeStartDateSemanticLabel()
  +String dateRangeEndDateSemanticLabel()
  -String _formatDayPeriod()
  +String formatDecimal()
  +String formatTimeOfDay()
  +String aboutListTileTitle()
  +String licensesPackageDetailText()
  +String pageRowsInfoTitle()
  +String tabLabel()
  +String selectedRowCountTitle()
  +TimeOfDayFormat timeOfDayFormat()
  {static} +Future<MaterialLocalizations> load()
  +String remainingTextFieldCharacterCount()
}

"flutter::lib::src::material::material_localizations.dart::DefaultMaterialLocalizations" o-- "flutter::lib::src::material::typography.dart::ScriptCategory"
"flutter::lib::src::material::material_localizations.dart::MaterialLocalizations" <|-- "flutter::lib::src::material::material_localizations.dart::DefaultMaterialLocalizations"


@enduml