@startuml
set namespaceSeparator ::

class "flutter::lib::src::material::selection_area.dart::SelectionArea" {
  +dynamic focusNode
  +dynamic selectionControls
  +dynamic child
  +dynamic createState()
}

class "flutter::lib::src::material::selection_area.dart::_SelectionAreaState" {
  -dynamic _internalNode
  -dynamic _effectiveFocusNode
  +void dispose()
  +dynamic build()
}


@enduml