@startuml
set namespaceSeparator ::

class "flutter::lib::src::cupertino::icons.dart::CupertinoIcons" {
  {static} +String iconFont
  {static} +String iconFontPackage
  {static} +dynamic left_chevron
  {static} +dynamic right_chevron
  {static} +dynamic share
  {static} +dynamic share_solid
  {static} +dynamic book
  {static} +dynamic book_solid
  {static} +dynamic bookmark
  {static} +dynamic bookmark_solid
  {static} +dynamic info
  {static} +dynamic reply
  {static} +dynamic conversation_bubble
  {static} +dynamic profile_circled
  {static} +dynamic plus_circled
  {static} +dynamic minus_circled
  {static} +dynamic flag
  {static} +dynamic search
  {static} +dynamic check_mark
  {static} +dynamic check_mark_circled
  {static} +dynamic check_mark_circled_solid
  {static} +dynamic circle
  {static} +dynamic circle_filled
  {static} +dynamic back
  {static} +dynamic forward
  {static} +dynamic home
  {static} +dynamic shopping_cart
  {static} +dynamic ellipsis
  {static} +dynamic phone
  {static} +dynamic phone_solid
  {static} +dynamic down_arrow
  {static} +dynamic up_arrow
  {static} +dynamic battery_charging
  {static} +dynamic battery_empty
  {static} +dynamic battery_full
  {static} +dynamic battery_75_percent
  {static} +dynamic battery_25_percent
  {static} +dynamic bluetooth
  {static} +dynamic restart
  {static} +dynamic reply_all
  {static} +dynamic reply_thick_solid
  {static} +dynamic share_up
  {static} +dynamic shuffle
  {static} +dynamic shuffle_medium
  {static} +dynamic shuffle_thick
  {static} +dynamic photo_camera
  {static} +dynamic photo_camera_solid
  {static} +dynamic video_camera
  {static} +dynamic video_camera_solid
  {static} +dynamic switch_camera
  {static} +dynamic switch_camera_solid
  {static} +dynamic collections
  {static} +dynamic collections_solid
  {static} +dynamic folder
  {static} +dynamic folder_solid
  {static} +dynamic folder_open
  {static} +dynamic delete
  {static} +dynamic delete_solid
  {static} +dynamic delete_simple
  {static} +dynamic pen
  {static} +dynamic pencil
  {static} +dynamic create
  {static} +dynamic create_solid
  {static} +dynamic refresh
  {static} +dynamic refresh_circled
  {static} +dynamic refresh_circled_solid
  {static} +dynamic refresh_thin
  {static} +dynamic refresh_thick
  {static} +dynamic refresh_bold
  {static} +dynamic clear_thick
  {static} +dynamic clear_thick_circled
  {static} +dynamic clear
  {static} +dynamic clear_circled
  {static} +dynamic clear_circled_solid
  {static} +dynamic add
  {static} +dynamic add_circled
  {static} +dynamic add_circled_solid
  {static} +dynamic gear
  {static} +dynamic gear_solid
  {static} +dynamic gear_big
  {static} +dynamic settings
  {static} +dynamic settings_solid
  {static} +dynamic music_note
  {static} +dynamic double_music_note
  {static} +dynamic play_arrow
  {static} +dynamic play_arrow_solid
  {static} +dynamic pause
  {static} +dynamic pause_solid
  {static} +dynamic loop
  {static} +dynamic loop_thick
  {static} +dynamic volume_down
  {static} +dynamic volume_mute
  {static} +dynamic volume_off
  {static} +dynamic volume_up
  {static} +dynamic fullscreen
  {static} +dynamic fullscreen_exit
  {static} +dynamic mic_off
  {static} +dynamic mic
  {static} +dynamic mic_solid
  {static} +dynamic clock
  {static} +dynamic clock_solid
  {static} +dynamic time
  {static} +dynamic time_solid
  {static} +dynamic padlock
  {static} +dynamic padlock_solid
  {static} +dynamic eye
  {static} +dynamic eye_solid
  {static} +dynamic person
  {static} +dynamic person_solid
  {static} +dynamic person_add
  {static} +dynamic person_add_solid
  {static} +dynamic group
  {static} +dynamic group_solid
  {static} +dynamic mail
  {static} +dynamic mail_solid
  {static} +dynamic location
  {static} +dynamic location_solid
  {static} +dynamic tag
  {static} +dynamic tag_solid
  {static} +dynamic tags
  {static} +dynamic tags_solid
  {static} +dynamic bus
  {static} +dynamic car
  {static} +dynamic car_detailed
  {static} +dynamic train_style_one
  {static} +dynamic train_style_two
  {static} +dynamic paw
  {static} +dynamic paw_solid
  {static} +dynamic game_controller
  {static} +dynamic game_controller_solid
  {static} +dynamic lab_flask
  {static} +dynamic lab_flask_solid
  {static} +dynamic heart
  {static} +dynamic heart_solid
  {static} +dynamic bell
  {static} +dynamic bell_solid
  {static} +dynamic news
  {static} +dynamic news_solid
  {static} +dynamic brightness
  {static} +dynamic brightness_solid
  {static} +dynamic airplane
  {static} +dynamic alarm
  {static} +dynamic alarm_fill
  {static} +dynamic alt
  {static} +dynamic ant
  {static} +dynamic ant_circle
  {static} +dynamic ant_circle_fill
  {static} +dynamic ant_fill
  {static} +dynamic antenna_radiowaves_left_right
  {static} +dynamic app
  {static} +dynamic app_badge
  {static} +dynamic app_badge_fill
  {static} +dynamic app_fill
  {static} +dynamic archivebox
  {static} +dynamic archivebox_fill
  {static} +dynamic arrow_2_circlepath
  {static} +dynamic arrow_2_circlepath_circle
  {static} +dynamic arrow_2_circlepath_circle_fill
  {static} +dynamic arrow_2_squarepath
  {static} +dynamic arrow_3_trianglepath
  {static} +dynamic arrow_branch
  {static} +dynamic arrow_clockwise
  {static} +dynamic arrow_clockwise_circle
  {static} +dynamic arrow_clockwise_circle_fill
  {static} +dynamic arrow_counterclockwise
  {static} +dynamic arrow_counterclockwise_circle
  {static} +dynamic arrow_counterclockwise_circle_fill
  {static} +dynamic arrow_down
  {static} +dynamic arrow_down_circle
  {static} +dynamic arrow_down_circle_fill
  {static} +dynamic arrow_down_doc
  {static} +dynamic arrow_down_doc_fill
  {static} +dynamic arrow_down_left
  {static} +dynamic arrow_down_left_circle
  {static} +dynamic arrow_down_left_circle_fill
  {static} +dynamic arrow_down_left_square
  {static} +dynamic arrow_down_left_square_fill
  {static} +dynamic arrow_down_right
  {static} +dynamic arrow_down_right_arrow_up_left
  {static} +dynamic arrow_down_right_circle
  {static} +dynamic arrow_down_right_circle_fill
  {static} +dynamic arrow_down_right_square
  {static} +dynamic arrow_down_right_square_fill
  {static} +dynamic arrow_down_square
  {static} +dynamic arrow_down_square_fill
  {static} +dynamic arrow_down_to_line
  {static} +dynamic arrow_down_to_line_alt
  {static} +dynamic arrow_left
  {static} +dynamic arrow_left_circle
  {static} +dynamic arrow_left_circle_fill
  {static} +dynamic arrow_left_right
  {static} +dynamic arrow_left_right_circle
  {static} +dynamic arrow_left_right_circle_fill
  {static} +dynamic arrow_left_right_square
  {static} +dynamic arrow_left_right_square_fill
  {static} +dynamic arrow_left_square
  {static} +dynamic arrow_left_square_fill
  {static} +dynamic arrow_left_to_line
  {static} +dynamic arrow_left_to_line_alt
  {static} +dynamic arrow_merge
  {static} +dynamic arrow_right
  {static} +dynamic arrow_right_arrow_left
  {static} +dynamic arrow_right_arrow_left_circle
  {static} +dynamic arrow_right_arrow_left_circle_fill
  {static} +dynamic arrow_right_arrow_left_square
  {static} +dynamic arrow_right_arrow_left_square_fill
  {static} +dynamic arrow_right_circle
  {static} +dynamic arrow_right_circle_fill
  {static} +dynamic arrow_right_square
  {static} +dynamic arrow_right_square_fill
  {static} +dynamic arrow_right_to_line
  {static} +dynamic arrow_right_to_line_alt
  {static} +dynamic arrow_swap
  {static} +dynamic arrow_turn_down_left
  {static} +dynamic arrow_turn_down_right
  {static} +dynamic arrow_turn_left_down
  {static} +dynamic arrow_turn_left_up
  {static} +dynamic arrow_turn_right_down
  {static} +dynamic arrow_turn_right_up
  {static} +dynamic arrow_turn_up_left
  {static} +dynamic arrow_turn_up_right
  {static} +dynamic arrow_up
  {static} +dynamic arrow_up_arrow_down
  {static} +dynamic arrow_up_arrow_down_circle
  {static} +dynamic arrow_up_arrow_down_circle_fill
  {static} +dynamic arrow_up_arrow_down_square
  {static} +dynamic arrow_up_arrow_down_square_fill
  {static} +dynamic arrow_up_bin
  {static} +dynamic arrow_up_bin_fill
  {static} +dynamic arrow_up_circle
  {static} +dynamic arrow_up_circle_fill
  {static} +dynamic arrow_up_doc
  {static} +dynamic arrow_up_doc_fill
  {static} +dynamic arrow_up_down
  {static} +dynamic arrow_up_down_circle
  {static} +dynamic arrow_up_down_circle_fill
  {static} +dynamic arrow_up_down_square
  {static} +dynamic arrow_up_down_square_fill
  {static} +dynamic arrow_up_left
  {static} +dynamic arrow_up_left_arrow_down_right
  {static} +dynamic arrow_up_left_circle
  {static} +dynamic arrow_up_left_circle_fill
  {static} +dynamic arrow_up_left_square
  {static} +dynamic arrow_up_left_square_fill
  {static} +dynamic arrow_up_right
  {static} +dynamic arrow_up_right_circle
  {static} +dynamic arrow_up_right_circle_fill
  {static} +dynamic arrow_up_right_diamond
  {static} +dynamic arrow_up_right_diamond_fill
  {static} +dynamic arrow_up_right_square
  {static} +dynamic arrow_up_right_square_fill
  {static} +dynamic arrow_up_square
  {static} +dynamic arrow_up_square_fill
  {static} +dynamic arrow_up_to_line
  {static} +dynamic arrow_up_to_line_alt
  {static} +dynamic arrow_uturn_down
  {static} +dynamic arrow_uturn_down_circle
  {static} +dynamic arrow_uturn_down_circle_fill
  {static} +dynamic arrow_uturn_down_square
  {static} +dynamic arrow_uturn_down_square_fill
  {static} +dynamic arrow_uturn_left
  {static} +dynamic arrow_uturn_left_circle
  {static} +dynamic arrow_uturn_left_circle_fill
  {static} +dynamic arrow_uturn_left_square
  {static} +dynamic arrow_uturn_left_square_fill
  {static} +dynamic arrow_uturn_right
  {static} +dynamic arrow_uturn_right_circle
  {static} +dynamic arrow_uturn_right_circle_fill
  {static} +dynamic arrow_uturn_right_square
  {static} +dynamic arrow_uturn_right_square_fill
  {static} +dynamic arrow_uturn_up
  {static} +dynamic arrow_uturn_up_circle
  {static} +dynamic arrow_uturn_up_circle_fill
  {static} +dynamic arrow_uturn_up_square
  {static} +dynamic arrow_uturn_up_square_fill
  {static} +dynamic arrowshape_turn_up_left
  {static} +dynamic arrowshape_turn_up_left_2
  {static} +dynamic arrowshape_turn_up_left_2_fill
  {static} +dynamic arrowshape_turn_up_left_circle
  {static} +dynamic arrowshape_turn_up_left_circle_fill
  {static} +dynamic arrowshape_turn_up_left_fill
  {static} +dynamic arrowshape_turn_up_right
  {static} +dynamic arrowshape_turn_up_right_circle
  {static} +dynamic arrowshape_turn_up_right_circle_fill
  {static} +dynamic arrowshape_turn_up_right_fill
  {static} +dynamic arrowtriangle_down
  {static} +dynamic arrowtriangle_down_circle
  {static} +dynamic arrowtriangle_down_circle_fill
  {static} +dynamic arrowtriangle_down_fill
  {static} +dynamic arrowtriangle_down_square
  {static} +dynamic arrowtriangle_down_square_fill
  {static} +dynamic arrowtriangle_left
  {static} +dynamic arrowtriangle_left_circle
  {static} +dynamic arrowtriangle_left_circle_fill
  {static} +dynamic arrowtriangle_left_fill
  {static} +dynamic arrowtriangle_left_square
  {static} +dynamic arrowtriangle_left_square_fill
  {static} +dynamic arrowtriangle_right
  {static} +dynamic arrowtriangle_right_circle
  {static} +dynamic arrowtriangle_right_circle_fill
  {static} +dynamic arrowtriangle_right_fill
  {static} +dynamic arrowtriangle_right_square
  {static} +dynamic arrowtriangle_right_square_fill
  {static} +dynamic arrowtriangle_up
  {static} +dynamic arrowtriangle_up_circle
  {static} +dynamic arrowtriangle_up_circle_fill
  {static} +dynamic arrowtriangle_up_fill
  {static} +dynamic arrowtriangle_up_square
  {static} +dynamic arrowtriangle_up_square_fill
  {static} +dynamic asterisk_circle
  {static} +dynamic asterisk_circle_fill
  {static} +dynamic at
  {static} +dynamic at_badge_minus
  {static} +dynamic at_badge_plus
  {static} +dynamic at_circle
  {static} +dynamic at_circle_fill
  {static} +dynamic backward
  {static} +dynamic backward_end
  {static} +dynamic backward_end_alt
  {static} +dynamic backward_end_alt_fill
  {static} +dynamic backward_end_fill
  {static} +dynamic backward_fill
  {static} +dynamic badge_plus_radiowaves_right
  {static} +dynamic bag
  {static} +dynamic bag_badge_minus
  {static} +dynamic bag_badge_plus
  {static} +dynamic bag_fill
  {static} +dynamic bag_fill_badge_minus
  {static} +dynamic bag_fill_badge_plus
  {static} +dynamic bandage
  {static} +dynamic bandage_fill
  {static} +dynamic barcode
  {static} +dynamic barcode_viewfinder
  {static} +dynamic bars
  {static} +dynamic battery_0
  {static} +dynamic battery_100
  {static} +dynamic battery_25
  {static} +dynamic bed_double
  {static} +dynamic bed_double_fill
  {static} +dynamic bell_circle
  {static} +dynamic bell_circle_fill
  {static} +dynamic bell_fill
  {static} +dynamic bell_slash
  {static} +dynamic bell_slash_fill
  {static} +dynamic bin_xmark
  {static} +dynamic bin_xmark_fill
  {static} +dynamic bitcoin
  {static} +dynamic bitcoin_circle
  {static} +dynamic bitcoin_circle_fill
  {static} +dynamic bold
  {static} +dynamic bold_italic_underline
  {static} +dynamic bold_underline
  {static} +dynamic bolt
  {static} +dynamic bolt_badge_a
  {static} +dynamic bolt_badge_a_fill
  {static} +dynamic bolt_circle
  {static} +dynamic bolt_circle_fill
  {static} +dynamic bolt_fill
  {static} +dynamic bolt_horizontal
  {static} +dynamic bolt_horizontal_circle
  {static} +dynamic bolt_horizontal_circle_fill
  {static} +dynamic bolt_horizontal_fill
  {static} +dynamic bolt_slash
  {static} +dynamic bolt_slash_fill
  {static} +dynamic book_circle
  {static} +dynamic book_circle_fill
  {static} +dynamic book_fill
  {static} +dynamic bookmark_fill
  {static} +dynamic briefcase
  {static} +dynamic briefcase_fill
  {static} +dynamic bubble_left
  {static} +dynamic bubble_left_bubble_right
  {static} +dynamic bubble_left_bubble_right_fill
  {static} +dynamic bubble_left_fill
  {static} +dynamic bubble_middle_bottom
  {static} +dynamic bubble_middle_bottom_fill
  {static} +dynamic bubble_middle_top
  {static} +dynamic bubble_middle_top_fill
  {static} +dynamic bubble_right
  {static} +dynamic bubble_right_fill
  {static} +dynamic building_2_fill
  {static} +dynamic burn
  {static} +dynamic burst
  {static} +dynamic burst_fill
  {static} +dynamic calendar
  {static} +dynamic calendar_badge_minus
  {static} +dynamic calendar_badge_plus
  {static} +dynamic calendar_circle
  {static} +dynamic calendar_circle_fill
  {static} +dynamic calendar_today
  {static} +dynamic camera
  {static} +dynamic camera_circle
  {static} +dynamic camera_circle_fill
  {static} +dynamic camera_fill
  {static} +dynamic camera_on_rectangle
  {static} +dynamic camera_on_rectangle_fill
  {static} +dynamic camera_rotate
  {static} +dynamic camera_rotate_fill
  {static} +dynamic camera_viewfinder
  {static} +dynamic capslock
  {static} +dynamic capslock_fill
  {static} +dynamic capsule
  {static} +dynamic capsule_fill
  {static} +dynamic captions_bubble
  {static} +dynamic captions_bubble_fill
  {static} +dynamic car_fill
  {static} +dynamic cart
  {static} +dynamic cart_badge_minus
  {static} +dynamic cart_badge_plus
  {static} +dynamic cart_fill
  {static} +dynamic cart_fill_badge_minus
  {static} +dynamic cart_fill_badge_plus
  {static} +dynamic chart_bar
  {static} +dynamic chart_bar_alt_fill
  {static} +dynamic chart_bar_circle
  {static} +dynamic chart_bar_circle_fill
  {static} +dynamic chart_bar_fill
  {static} +dynamic chart_bar_square
  {static} +dynamic chart_bar_square_fill
  {static} +dynamic chart_pie
  {static} +dynamic chart_pie_fill
  {static} +dynamic chat_bubble
  {static} +dynamic chat_bubble_2
  {static} +dynamic chat_bubble_2_fill
  {static} +dynamic chat_bubble_fill
  {static} +dynamic chat_bubble_text
  {static} +dynamic chat_bubble_text_fill
  {static} +dynamic checkmark
  {static} +dynamic checkmark_alt
  {static} +dynamic checkmark_alt_circle
  {static} +dynamic checkmark_alt_circle_fill
  {static} +dynamic checkmark_circle
  {static} +dynamic checkmark_circle_fill
  {static} +dynamic checkmark_rectangle
  {static} +dynamic checkmark_rectangle_fill
  {static} +dynamic checkmark_seal
  {static} +dynamic checkmark_seal_fill
  {static} +dynamic checkmark_shield
  {static} +dynamic checkmark_shield_fill
  {static} +dynamic checkmark_square
  {static} +dynamic checkmark_square_fill
  {static} +dynamic chevron_back
  {static} +dynamic chevron_compact_down
  {static} +dynamic chevron_compact_left
  {static} +dynamic chevron_compact_right
  {static} +dynamic chevron_compact_up
  {static} +dynamic chevron_down
  {static} +dynamic chevron_down_circle
  {static} +dynamic chevron_down_circle_fill
  {static} +dynamic chevron_down_square
  {static} +dynamic chevron_down_square_fill
  {static} +dynamic chevron_forward
  {static} +dynamic chevron_left
  {static} +dynamic chevron_left_2
  {static} +dynamic chevron_left_circle
  {static} +dynamic chevron_left_circle_fill
  {static} +dynamic chevron_left_slash_chevron_right
  {static} +dynamic chevron_left_square
  {static} +dynamic chevron_left_square_fill
  {static} +dynamic chevron_right
  {static} +dynamic chevron_right_2
  {static} +dynamic chevron_right_circle
  {static} +dynamic chevron_right_circle_fill
  {static} +dynamic chevron_right_square
  {static} +dynamic chevron_right_square_fill
  {static} +dynamic chevron_up
  {static} +dynamic chevron_up_chevron_down
  {static} +dynamic chevron_up_circle
  {static} +dynamic chevron_up_circle_fill
  {static} +dynamic chevron_up_square
  {static} +dynamic chevron_up_square_fill
  {static} +dynamic circle_bottomthird_split
  {static} +dynamic circle_fill
  {static} +dynamic circle_grid_3x3
  {static} +dynamic circle_grid_3x3_fill
  {static} +dynamic circle_grid_hex
  {static} +dynamic circle_grid_hex_fill
  {static} +dynamic circle_lefthalf_fill
  {static} +dynamic circle_righthalf_fill
  {static} +dynamic clear_fill
  {static} +dynamic clock_fill
  {static} +dynamic cloud
  {static} +dynamic cloud_bolt
  {static} +dynamic cloud_bolt_fill
  {static} +dynamic cloud_bolt_rain
  {static} +dynamic cloud_bolt_rain_fill
  {static} +dynamic cloud_download
  {static} +dynamic cloud_download_fill
  {static} +dynamic cloud_drizzle
  {static} +dynamic cloud_drizzle_fill
  {static} +dynamic cloud_fill
  {static} +dynamic cloud_fog
  {static} +dynamic cloud_fog_fill
  {static} +dynamic cloud_hail
  {static} +dynamic cloud_hail_fill
  {static} +dynamic cloud_heavyrain
  {static} +dynamic cloud_heavyrain_fill
  {static} +dynamic cloud_moon
  {static} +dynamic cloud_moon_bolt
  {static} +dynamic cloud_moon_bolt_fill
  {static} +dynamic cloud_moon_fill
  {static} +dynamic cloud_moon_rain
  {static} +dynamic cloud_moon_rain_fill
  {static} +dynamic cloud_rain
  {static} +dynamic cloud_rain_fill
  {static} +dynamic cloud_sleet
  {static} +dynamic cloud_sleet_fill
  {static} +dynamic cloud_snow
  {static} +dynamic cloud_snow_fill
  {static} +dynamic cloud_sun
  {static} +dynamic cloud_sun_bolt
  {static} +dynamic cloud_sun_bolt_fill
  {static} +dynamic cloud_sun_fill
  {static} +dynamic cloud_sun_rain
  {static} +dynamic cloud_sun_rain_fill
  {static} +dynamic cloud_upload
  {static} +dynamic cloud_upload_fill
  {static} +dynamic color_filter
  {static} +dynamic color_filter_fill
  {static} +dynamic command
  {static} +dynamic compass
  {static} +dynamic compass_fill
  {static} +dynamic control
  {static} +dynamic creditcard
  {static} +dynamic creditcard_fill
  {static} +dynamic crop
  {static} +dynamic crop_rotate
  {static} +dynamic cube
  {static} +dynamic cube_box
  {static} +dynamic cube_box_fill
  {static} +dynamic cube_fill
  {static} +dynamic cursor_rays
  {static} +dynamic decrease_indent
  {static} +dynamic decrease_quotelevel
  {static} +dynamic delete_left
  {static} +dynamic delete_left_fill
  {static} +dynamic delete_right
  {static} +dynamic delete_right_fill
  {static} +dynamic desktopcomputer
  {static} +dynamic device_desktop
  {static} +dynamic device_laptop
  {static} +dynamic device_phone_landscape
  {static} +dynamic device_phone_portrait
  {static} +dynamic dial
  {static} +dynamic dial_fill
  {static} +dynamic divide
  {static} +dynamic divide_circle
  {static} +dynamic divide_circle_fill
  {static} +dynamic divide_square
  {static} +dynamic divide_square_fill
  {static} +dynamic doc
  {static} +dynamic doc_append
  {static} +dynamic doc_chart
  {static} +dynamic doc_chart_fill
  {static} +dynamic doc_checkmark
  {static} +dynamic doc_checkmark_fill
  {static} +dynamic doc_circle
  {static} +dynamic doc_circle_fill
  {static} +dynamic doc_fill
  {static} +dynamic doc_on_clipboard
  {static} +dynamic doc_on_clipboard_fill
  {static} +dynamic doc_on_doc
  {static} +dynamic doc_on_doc_fill
  {static} +dynamic doc_person
  {static} +dynamic doc_person_fill
  {static} +dynamic doc_plaintext
  {static} +dynamic doc_richtext
  {static} +dynamic doc_text
  {static} +dynamic doc_text_fill
  {static} +dynamic doc_text_search
  {static} +dynamic doc_text_viewfinder
  {static} +dynamic dot_radiowaves_left_right
  {static} +dynamic dot_radiowaves_right
  {static} +dynamic dot_square
  {static} +dynamic dot_square_fill
  {static} +dynamic download_circle
  {static} +dynamic download_circle_fill
  {static} +dynamic drop
  {static} +dynamic drop_fill
  {static} +dynamic drop_triangle
  {static} +dynamic drop_triangle_fill
  {static} +dynamic ear
  {static} +dynamic eject
  {static} +dynamic eject_fill
  {static} +dynamic ellipses_bubble
  {static} +dynamic ellipses_bubble_fill
  {static} +dynamic ellipsis_circle
  {static} +dynamic ellipsis_circle_fill
  {static} +dynamic ellipsis_vertical
  {static} +dynamic ellipsis_vertical_circle
  {static} +dynamic ellipsis_vertical_circle_fill
  {static} +dynamic envelope
  {static} +dynamic envelope_badge
  {static} +dynamic envelope_badge_fill
  {static} +dynamic envelope_circle
  {static} +dynamic envelope_circle_fill
  {static} +dynamic envelope_fill
  {static} +dynamic envelope_open
  {static} +dynamic envelope_open_fill
  {static} +dynamic equal
  {static} +dynamic equal_circle
  {static} +dynamic equal_circle_fill
  {static} +dynamic equal_square
  {static} +dynamic equal_square_fill
  {static} +dynamic escape
  {static} +dynamic exclamationmark
  {static} +dynamic exclamationmark_bubble
  {static} +dynamic exclamationmark_bubble_fill
  {static} +dynamic exclamationmark_circle
  {static} +dynamic exclamationmark_circle_fill
  {static} +dynamic exclamationmark_octagon
  {static} +dynamic exclamationmark_octagon_fill
  {static} +dynamic exclamationmark_shield
  {static} +dynamic exclamationmark_shield_fill
  {static} +dynamic exclamationmark_square
  {static} +dynamic exclamationmark_square_fill
  {static} +dynamic exclamationmark_triangle
  {static} +dynamic exclamationmark_triangle_fill
  {static} +dynamic eye_fill
  {static} +dynamic eye_slash
  {static} +dynamic eye_slash_fill
  {static} +dynamic eyedropper
  {static} +dynamic eyedropper_full
  {static} +dynamic eyedropper_halffull
  {static} +dynamic eyeglasses
  {static} +dynamic f_cursive
  {static} +dynamic f_cursive_circle
  {static} +dynamic f_cursive_circle_fill
  {static} +dynamic film
  {static} +dynamic film_fill
  {static} +dynamic flag_circle
  {static} +dynamic flag_circle_fill
  {static} +dynamic flag_fill
  {static} +dynamic flag_slash
  {static} +dynamic flag_slash_fill
  {static} +dynamic flame
  {static} +dynamic flame_fill
  {static} +dynamic floppy_disk
  {static} +dynamic flowchart
  {static} +dynamic flowchart_fill
  {static} +dynamic folder_badge_minus
  {static} +dynamic folder_badge_person_crop
  {static} +dynamic folder_badge_plus
  {static} +dynamic folder_circle
  {static} +dynamic folder_circle_fill
  {static} +dynamic folder_fill
  {static} +dynamic folder_fill_badge_minus
  {static} +dynamic folder_fill_badge_person_crop
  {static} +dynamic folder_fill_badge_plus
  {static} +dynamic forward_end
  {static} +dynamic forward_end_alt
  {static} +dynamic forward_end_alt_fill
  {static} +dynamic forward_end_fill
  {static} +dynamic forward_fill
  {static} +dynamic function
  {static} +dynamic fx
  {static} +dynamic gamecontroller
  {static} +dynamic gamecontroller_alt_fill
  {static} +dynamic gamecontroller_fill
  {static} +dynamic gauge
  {static} +dynamic gauge_badge_minus
  {static} +dynamic gauge_badge_plus
  {static} +dynamic gear_alt
  {static} +dynamic gear_alt_fill
  {static} +dynamic gift
  {static} +dynamic gift_alt
  {static} +dynamic gift_alt_fill
  {static} +dynamic gift_fill
  {static} +dynamic globe
  {static} +dynamic gobackward
  {static} +dynamic gobackward_10
  {static} +dynamic gobackward_15
  {static} +dynamic gobackward_30
  {static} +dynamic gobackward_45
  {static} +dynamic gobackward_60
  {static} +dynamic gobackward_75
  {static} +dynamic gobackward_90
  {static} +dynamic gobackward_minus
  {static} +dynamic goforward
  {static} +dynamic goforward_10
  {static} +dynamic goforward_15
  {static} +dynamic goforward_30
  {static} +dynamic goforward_45
  {static} +dynamic goforward_60
  {static} +dynamic goforward_75
  {static} +dynamic goforward_90
  {static} +dynamic goforward_plus
  {static} +dynamic graph_circle
  {static} +dynamic graph_circle_fill
  {static} +dynamic graph_square
  {static} +dynamic graph_square_fill
  {static} +dynamic greaterthan
  {static} +dynamic greaterthan_circle
  {static} +dynamic greaterthan_circle_fill
  {static} +dynamic greaterthan_square
  {static} +dynamic greaterthan_square_fill
  {static} +dynamic grid
  {static} +dynamic grid_circle
  {static} +dynamic grid_circle_fill
  {static} +dynamic guitars
  {static} +dynamic hammer
  {static} +dynamic hammer_fill
  {static} +dynamic hand_draw
  {static} +dynamic hand_draw_fill
  {static} +dynamic hand_point_left
  {static} +dynamic hand_point_left_fill
  {static} +dynamic hand_point_right
  {static} +dynamic hand_point_right_fill
  {static} +dynamic hand_raised
  {static} +dynamic hand_raised_fill
  {static} +dynamic hand_raised_slash
  {static} +dynamic hand_raised_slash_fill
  {static} +dynamic hand_thumbsdown
  {static} +dynamic hand_thumbsdown_fill
  {static} +dynamic hand_thumbsup
  {static} +dynamic hand_thumbsup_fill
  {static} +dynamic hare
  {static} +dynamic hare_fill
  {static} +dynamic headphones
  {static} +dynamic heart_circle
  {static} +dynamic heart_circle_fill
  {static} +dynamic heart_fill
  {static} +dynamic heart_slash
  {static} +dynamic heart_slash_circle
  {static} +dynamic heart_slash_circle_fill
  {static} +dynamic heart_slash_fill
  {static} +dynamic helm
  {static} +dynamic hexagon
  {static} +dynamic hexagon_fill
  {static} +dynamic hifispeaker
  {static} +dynamic hifispeaker_fill
  {static} +dynamic hourglass
  {static} +dynamic hourglass_bottomhalf_fill
  {static} +dynamic hourglass_tophalf_fill
  {static} +dynamic house
  {static} +dynamic house_alt
  {static} +dynamic house_alt_fill
  {static} +dynamic house_fill
  {static} +dynamic hurricane
  {static} +dynamic increase_indent
  {static} +dynamic increase_quotelevel
  {static} +dynamic infinite
  {static} +dynamic info_circle
  {static} +dynamic info_circle_fill
  {static} +dynamic italic
  {static} +dynamic keyboard
  {static} +dynamic keyboard_chevron_compact_down
  {static} +dynamic largecircle_fill_circle
  {static} +dynamic lasso
  {static} +dynamic layers
  {static} +dynamic layers_alt
  {static} +dynamic layers_alt_fill
  {static} +dynamic layers_fill
  {static} +dynamic leaf_arrow_circlepath
  {static} +dynamic lessthan
  {static} +dynamic lessthan_circle
  {static} +dynamic lessthan_circle_fill
  {static} +dynamic lessthan_square
  {static} +dynamic lessthan_square_fill
  {static} +dynamic light_max
  {static} +dynamic light_min
  {static} +dynamic lightbulb
  {static} +dynamic lightbulb_fill
  {static} +dynamic lightbulb_slash
  {static} +dynamic lightbulb_slash_fill
  {static} +dynamic line_horizontal_3
  {static} +dynamic line_horizontal_3_decrease
  {static} +dynamic line_horizontal_3_decrease_circle
  {static} +dynamic line_horizontal_3_decrease_circle_fill
  {static} +dynamic link
  {static} +dynamic link_circle
  {static} +dynamic link_circle_fill
  {static} +dynamic list_bullet
  {static} +dynamic list_bullet_below_rectangle
  {static} +dynamic list_bullet_indent
  {static} +dynamic list_dash
  {static} +dynamic list_number
  {static} +dynamic list_number_rtl
  {static} +dynamic location_circle
  {static} +dynamic location_circle_fill
  {static} +dynamic location_fill
  {static} +dynamic location_north
  {static} +dynamic location_north_fill
  {static} +dynamic location_north_line
  {static} +dynamic location_north_line_fill
  {static} +dynamic location_slash
  {static} +dynamic location_slash_fill
  {static} +dynamic lock
  {static} +dynamic lock_circle
  {static} +dynamic lock_circle_fill
  {static} +dynamic lock_fill
  {static} +dynamic lock_open
  {static} +dynamic lock_open_fill
  {static} +dynamic lock_rotation
  {static} +dynamic lock_rotation_open
  {static} +dynamic lock_shield
  {static} +dynamic lock_shield_fill
  {static} +dynamic lock_slash
  {static} +dynamic lock_slash_fill
  {static} +dynamic macwindow
  {static} +dynamic map
  {static} +dynamic map_fill
  {static} +dynamic map_pin
  {static} +dynamic map_pin_ellipse
  {static} +dynamic map_pin_slash
  {static} +dynamic memories
  {static} +dynamic memories_badge_minus
  {static} +dynamic memories_badge_plus
  {static} +dynamic metronome
  {static} +dynamic mic_circle
  {static} +dynamic mic_circle_fill
  {static} +dynamic mic_fill
  {static} +dynamic mic_slash
  {static} +dynamic mic_slash_fill
  {static} +dynamic minus
  {static} +dynamic minus_circle
  {static} +dynamic minus_circle_fill
  {static} +dynamic minus_rectangle
  {static} +dynamic minus_rectangle_fill
  {static} +dynamic minus_slash_plus
  {static} +dynamic minus_square
  {static} +dynamic minus_square_fill
  {static} +dynamic money_dollar
  {static} +dynamic money_dollar_circle
  {static} +dynamic money_dollar_circle_fill
  {static} +dynamic money_euro
  {static} +dynamic money_euro_circle
  {static} +dynamic money_euro_circle_fill
  {static} +dynamic money_pound
  {static} +dynamic money_pound_circle
  {static} +dynamic money_pound_circle_fill
  {static} +dynamic money_rubl
  {static} +dynamic money_rubl_circle
  {static} +dynamic money_rubl_circle_fill
  {static} +dynamic money_yen
  {static} +dynamic money_yen_circle
  {static} +dynamic money_yen_circle_fill
  {static} +dynamic moon
  {static} +dynamic moon_circle
  {static} +dynamic moon_circle_fill
  {static} +dynamic moon_fill
  {static} +dynamic moon_stars
  {static} +dynamic moon_stars_fill
  {static} +dynamic moon_zzz
  {static} +dynamic moon_zzz_fill
  {static} +dynamic move
  {static} +dynamic multiply
  {static} +dynamic multiply_circle
  {static} +dynamic multiply_circle_fill
  {static} +dynamic multiply_square
  {static} +dynamic multiply_square_fill
  {static} +dynamic music_albums
  {static} +dynamic music_albums_fill
  {static} +dynamic music_house
  {static} +dynamic music_house_fill
  {static} +dynamic music_mic
  {static} +dynamic music_note_2
  {static} +dynamic music_note_list
  {static} +dynamic nosign
  {static} +dynamic number
  {static} +dynamic number_circle
  {static} +dynamic number_circle_fill
  {static} +dynamic number_square
  {static} +dynamic number_square_fill
  {static} +dynamic option
  {static} +dynamic paintbrush
  {static} +dynamic paintbrush_fill
  {static} +dynamic pano
  {static} +dynamic pano_fill
  {static} +dynamic paperclip
  {static} +dynamic paperplane
  {static} +dynamic paperplane_fill
  {static} +dynamic paragraph
  {static} +dynamic pause_circle
  {static} +dynamic pause_circle_fill
  {static} +dynamic pause_fill
  {static} +dynamic pause_rectangle
  {static} +dynamic pause_rectangle_fill
  {static} +dynamic pencil_circle
  {static} +dynamic pencil_circle_fill
  {static} +dynamic pencil_ellipsis_rectangle
  {static} +dynamic pencil_outline
  {static} +dynamic pencil_slash
  {static} +dynamic percent
  {static} +dynamic person_2
  {static} +dynamic person_2_alt
  {static} +dynamic person_2_fill
  {static} +dynamic person_2_square_stack
  {static} +dynamic person_2_square_stack_fill
  {static} +dynamic person_3
  {static} +dynamic person_3_fill
  {static} +dynamic person_alt
  {static} +dynamic person_alt_circle
  {static} +dynamic person_alt_circle_fill
  {static} +dynamic person_badge_minus
  {static} +dynamic person_badge_minus_fill
  {static} +dynamic person_badge_plus
  {static} +dynamic person_badge_plus_fill
  {static} +dynamic person_circle
  {static} +dynamic person_circle_fill
  {static} +dynamic person_crop_circle
  {static} +dynamic person_crop_circle_badge_checkmark
  {static} +dynamic person_crop_circle_badge_exclam
  {static} +dynamic person_crop_circle_badge_minus
  {static} +dynamic person_crop_circle_badge_plus
  {static} +dynamic person_crop_circle_badge_xmark
  {static} +dynamic person_crop_circle_fill
  {static} +dynamic person_crop_circle_fill_badge_checkmark
  {static} +dynamic person_crop_circle_fill_badge_exclam
  {static} +dynamic person_crop_circle_fill_badge_minus
  {static} +dynamic person_crop_circle_fill_badge_plus
  {static} +dynamic person_crop_circle_fill_badge_xmark
  {static} +dynamic person_crop_rectangle
  {static} +dynamic person_crop_rectangle_fill
  {static} +dynamic person_crop_square
  {static} +dynamic person_crop_square_fill
  {static} +dynamic person_fill
  {static} +dynamic personalhotspot
  {static} +dynamic perspective
  {static} +dynamic phone_arrow_down_left
  {static} +dynamic phone_arrow_right
  {static} +dynamic phone_arrow_up_right
  {static} +dynamic phone_badge_plus
  {static} +dynamic phone_circle
  {static} +dynamic phone_circle_fill
  {static} +dynamic phone_down
  {static} +dynamic phone_down_circle
  {static} +dynamic phone_down_circle_fill
  {static} +dynamic phone_down_fill
  {static} +dynamic phone_fill
  {static} +dynamic phone_fill_arrow_down_left
  {static} +dynamic phone_fill_arrow_right
  {static} +dynamic phone_fill_arrow_up_right
  {static} +dynamic phone_fill_badge_plus
  {static} +dynamic photo
  {static} +dynamic photo_fill
  {static} +dynamic photo_fill_on_rectangle_fill
  {static} +dynamic photo_on_rectangle
  {static} +dynamic piano
  {static} +dynamic pin
  {static} +dynamic pin_fill
  {static} +dynamic pin_slash
  {static} +dynamic pin_slash_fill
  {static} +dynamic placemark
  {static} +dynamic placemark_fill
  {static} +dynamic play
  {static} +dynamic play_circle
  {static} +dynamic play_circle_fill
  {static} +dynamic play_fill
  {static} +dynamic play_rectangle
  {static} +dynamic play_rectangle_fill
  {static} +dynamic playpause
  {static} +dynamic playpause_fill
  {static} +dynamic plus
  {static} +dynamic plus_app
  {static} +dynamic plus_app_fill
  {static} +dynamic plus_bubble
  {static} +dynamic plus_bubble_fill
  {static} +dynamic plus_circle
  {static} +dynamic plus_circle_fill
  {static} +dynamic plus_rectangle
  {static} +dynamic plus_rectangle_fill
  {static} +dynamic plus_rectangle_fill_on_rectangle_fill
  {static} +dynamic plus_rectangle_on_rectangle
  {static} +dynamic plus_slash_minus
  {static} +dynamic plus_square
  {static} +dynamic plus_square_fill
  {static} +dynamic plus_square_fill_on_square_fill
  {static} +dynamic plus_square_on_square
  {static} +dynamic plusminus
  {static} +dynamic plusminus_circle
  {static} +dynamic plusminus_circle_fill
  {static} +dynamic power
  {static} +dynamic printer
  {static} +dynamic printer_fill
  {static} +dynamic projective
  {static} +dynamic purchased
  {static} +dynamic purchased_circle
  {static} +dynamic purchased_circle_fill
  {static} +dynamic qrcode
  {static} +dynamic qrcode_viewfinder
  {static} +dynamic question
  {static} +dynamic question_circle
  {static} +dynamic question_circle_fill
  {static} +dynamic question_diamond
  {static} +dynamic question_diamond_fill
  {static} +dynamic question_square
  {static} +dynamic question_square_fill
  {static} +dynamic quote_bubble
  {static} +dynamic quote_bubble_fill
  {static} +dynamic radiowaves_left
  {static} +dynamic radiowaves_right
  {static} +dynamic rays
  {static} +dynamic recordingtape
  {static} +dynamic rectangle
  {static} +dynamic rectangle_3_offgrid
  {static} +dynamic rectangle_3_offgrid_fill
  {static} +dynamic rectangle_arrow_up_right_arrow_down_left
  {static} +dynamic rectangle_arrow_up_right_arrow_down_left_slash
  {static} +dynamic rectangle_badge_checkmark
  {static} +dynamic rectangle_badge_xmark
  {static} +dynamic rectangle_compress_vertical
  {static} +dynamic rectangle_dock
  {static} +dynamic rectangle_expand_vertical
  {static} +dynamic rectangle_fill
  {static} +dynamic rectangle_fill_badge_checkmark
  {static} +dynamic rectangle_fill_badge_xmark
  {static} +dynamic rectangle_fill_on_rectangle_angled_fill
  {static} +dynamic rectangle_fill_on_rectangle_fill
  {static} +dynamic rectangle_grid_1x2
  {static} +dynamic rectangle_grid_1x2_fill
  {static} +dynamic rectangle_grid_2x2
  {static} +dynamic rectangle_grid_2x2_fill
  {static} +dynamic rectangle_grid_3x2
  {static} +dynamic rectangle_grid_3x2_fill
  {static} +dynamic rectangle_on_rectangle
  {static} +dynamic rectangle_on_rectangle_angled
  {static} +dynamic rectangle_paperclip
  {static} +dynamic rectangle_split_3x1
  {static} +dynamic rectangle_split_3x1_fill
  {static} +dynamic rectangle_split_3x3
  {static} +dynamic rectangle_split_3x3_fill
  {static} +dynamic rectangle_stack
  {static} +dynamic rectangle_stack_badge_minus
  {static} +dynamic rectangle_stack_badge_person_crop
  {static} +dynamic rectangle_stack_badge_plus
  {static} +dynamic rectangle_stack_fill
  {static} +dynamic rectangle_stack_fill_badge_minus
  {static} +dynamic rectangle_stack_fill_badge_person_crop
  {static} +dynamic rectangle_stack_fill_badge_plus
  {static} +dynamic rectangle_stack_person_crop
  {static} +dynamic rectangle_stack_person_crop_fill
  {static} +dynamic repeat
  {static} +dynamic repeat_1
  {static} +dynamic resize
  {static} +dynamic resize_h
  {static} +dynamic resize_v
  {static} +dynamic return_icon
  {static} +dynamic rhombus
  {static} +dynamic rhombus_fill
  {static} +dynamic rocket
  {static} +dynamic rocket_fill
  {static} +dynamic rosette
  {static} +dynamic rotate_left
  {static} +dynamic rotate_left_fill
  {static} +dynamic rotate_right
  {static} +dynamic rotate_right_fill
  {static} +dynamic scissors
  {static} +dynamic scissors_alt
  {static} +dynamic scope
  {static} +dynamic scribble
  {static} +dynamic search_circle
  {static} +dynamic search_circle_fill
  {static} +dynamic selection_pin_in_out
  {static} +dynamic shield
  {static} +dynamic shield_fill
  {static} +dynamic shield_lefthalf_fill
  {static} +dynamic shield_slash
  {static} +dynamic shield_slash_fill
  {static} +dynamic shift
  {static} +dynamic shift_fill
  {static} +dynamic sidebar_left
  {static} +dynamic sidebar_right
  {static} +dynamic signature
  {static} +dynamic skew
  {static} +dynamic slash_circle
  {static} +dynamic slash_circle_fill
  {static} +dynamic slider_horizontal_3
  {static} +dynamic slider_horizontal_below_rectangle
  {static} +dynamic slowmo
  {static} +dynamic smallcircle_circle
  {static} +dynamic smallcircle_circle_fill
  {static} +dynamic smallcircle_fill_circle
  {static} +dynamic smallcircle_fill_circle_fill
  {static} +dynamic smiley
  {static} +dynamic smiley_fill
  {static} +dynamic smoke
  {static} +dynamic smoke_fill
  {static} +dynamic snow
  {static} +dynamic sort_down
  {static} +dynamic sort_down_circle
  {static} +dynamic sort_down_circle_fill
  {static} +dynamic sort_up
  {static} +dynamic sort_up_circle
  {static} +dynamic sort_up_circle_fill
  {static} +dynamic sparkles
  {static} +dynamic speaker
  {static} +dynamic speaker_1
  {static} +dynamic speaker_1_fill
  {static} +dynamic speaker_2
  {static} +dynamic speaker_2_fill
  {static} +dynamic speaker_3
  {static} +dynamic speaker_3_fill
  {static} +dynamic speaker_fill
  {static} +dynamic speaker_slash
  {static} +dynamic speaker_slash_fill
  {static} +dynamic speaker_slash_fill_rtl
  {static} +dynamic speaker_slash_rtl
  {static} +dynamic speaker_zzz
  {static} +dynamic speaker_zzz_fill
  {static} +dynamic speaker_zzz_fill_rtl
  {static} +dynamic speaker_zzz_rtl
  {static} +dynamic speedometer
  {static} +dynamic sportscourt
  {static} +dynamic sportscourt_fill
  {static} +dynamic square
  {static} +dynamic square_arrow_down
  {static} +dynamic square_arrow_down_fill
  {static} +dynamic square_arrow_down_on_square
  {static} +dynamic square_arrow_down_on_square_fill
  {static} +dynamic square_arrow_left
  {static} +dynamic square_arrow_left_fill
  {static} +dynamic square_arrow_right
  {static} +dynamic square_arrow_right_fill
  {static} +dynamic square_arrow_up
  {static} +dynamic square_arrow_up_fill
  {static} +dynamic square_arrow_up_on_square
  {static} +dynamic square_arrow_up_on_square_fill
  {static} +dynamic square_favorites
  {static} +dynamic square_favorites_alt
  {static} +dynamic square_favorites_alt_fill
  {static} +dynamic square_favorites_fill
  {static} +dynamic square_fill
  {static} +dynamic square_fill_line_vertical_square
  {static} +dynamic square_fill_line_vertical_square_fill
  {static} +dynamic square_fill_on_circle_fill
  {static} +dynamic square_fill_on_square_fill
  {static} +dynamic square_grid_2x2
  {static} +dynamic square_grid_2x2_fill
  {static} +dynamic square_grid_3x2
  {static} +dynamic square_grid_3x2_fill
  {static} +dynamic square_grid_4x3_fill
  {static} +dynamic square_lefthalf_fill
  {static} +dynamic square_line_vertical_square
  {static} +dynamic square_line_vertical_square_fill
  {static} +dynamic square_list
  {static} +dynamic square_list_fill
  {static} +dynamic square_on_circle
  {static} +dynamic square_on_square
  {static} +dynamic square_pencil
  {static} +dynamic square_pencil_fill
  {static} +dynamic square_righthalf_fill
  {static} +dynamic square_split_1x2
  {static} +dynamic square_split_1x2_fill
  {static} +dynamic square_split_2x1
  {static} +dynamic square_split_2x1_fill
  {static} +dynamic square_split_2x2
  {static} +dynamic square_split_2x2_fill
  {static} +dynamic square_stack
  {static} +dynamic square_stack_3d_down_dottedline
  {static} +dynamic square_stack_3d_down_right
  {static} +dynamic square_stack_3d_down_right_fill
  {static} +dynamic square_stack_3d_up
  {static} +dynamic square_stack_3d_up_fill
  {static} +dynamic square_stack_3d_up_slash
  {static} +dynamic square_stack_3d_up_slash_fill
  {static} +dynamic square_stack_fill
  {static} +dynamic squares_below_rectangle
  {static} +dynamic star
  {static} +dynamic star_circle
  {static} +dynamic star_circle_fill
  {static} +dynamic star_fill
  {static} +dynamic star_lefthalf_fill
  {static} +dynamic star_slash
  {static} +dynamic star_slash_fill
  {static} +dynamic staroflife
  {static} +dynamic staroflife_fill
  {static} +dynamic stop
  {static} +dynamic stop_circle
  {static} +dynamic stop_circle_fill
  {static} +dynamic stop_fill
  {static} +dynamic stopwatch
  {static} +dynamic stopwatch_fill
  {static} +dynamic strikethrough
  {static} +dynamic suit_club
  {static} +dynamic suit_club_fill
  {static} +dynamic suit_diamond
  {static} +dynamic suit_diamond_fill
  {static} +dynamic suit_heart
  {static} +dynamic suit_heart_fill
  {static} +dynamic suit_spade
  {static} +dynamic suit_spade_fill
  {static} +dynamic sum
  {static} +dynamic sun_dust
  {static} +dynamic sun_dust_fill
  {static} +dynamic sun_haze
  {static} +dynamic sun_haze_fill
  {static} +dynamic sun_max
  {static} +dynamic sun_max_fill
  {static} +dynamic sun_min
  {static} +dynamic sun_min_fill
  {static} +dynamic sunrise
  {static} +dynamic sunrise_fill
  {static} +dynamic sunset
  {static} +dynamic sunset_fill
  {static} +dynamic t_bubble
  {static} +dynamic t_bubble_fill
  {static} +dynamic table
  {static} +dynamic table_badge_more
  {static} +dynamic table_badge_more_fill
  {static} +dynamic table_fill
  {static} +dynamic tag_circle
  {static} +dynamic tag_circle_fill
  {static} +dynamic tag_fill
  {static} +dynamic text_aligncenter
  {static} +dynamic text_alignleft
  {static} +dynamic text_alignright
  {static} +dynamic text_append
  {static} +dynamic text_badge_checkmark
  {static} +dynamic text_badge_minus
  {static} +dynamic text_badge_plus
  {static} +dynamic text_badge_star
  {static} +dynamic text_badge_xmark
  {static} +dynamic text_bubble
  {static} +dynamic text_bubble_fill
  {static} +dynamic text_cursor
  {static} +dynamic text_insert
  {static} +dynamic text_justify
  {static} +dynamic text_justifyleft
  {static} +dynamic text_justifyright
  {static} +dynamic text_quote
  {static} +dynamic textbox
  {static} +dynamic textformat
  {static} +dynamic textformat_123
  {static} +dynamic textformat_abc
  {static} +dynamic textformat_abc_dottedunderline
  {static} +dynamic textformat_alt
  {static} +dynamic textformat_size
  {static} +dynamic textformat_subscript
  {static} +dynamic textformat_superscript
  {static} +dynamic thermometer
  {static} +dynamic thermometer_snowflake
  {static} +dynamic thermometer_sun
  {static} +dynamic ticket
  {static} +dynamic ticket_fill
  {static} +dynamic tickets
  {static} +dynamic tickets_fill
  {static} +dynamic timelapse
  {static} +dynamic timer
  {static} +dynamic timer_fill
  {static} +dynamic today
  {static} +dynamic today_fill
  {static} +dynamic tornado
  {static} +dynamic tortoise
  {static} +dynamic tortoise_fill
  {static} +dynamic tram_fill
  {static} +dynamic trash
  {static} +dynamic trash_circle
  {static} +dynamic trash_circle_fill
  {static} +dynamic trash_fill
  {static} +dynamic trash_slash
  {static} +dynamic trash_slash_fill
  {static} +dynamic tray
  {static} +dynamic tray_2
  {static} +dynamic tray_2_fill
  {static} +dynamic tray_arrow_down
  {static} +dynamic tray_arrow_down_fill
  {static} +dynamic tray_arrow_up
  {static} +dynamic tray_arrow_up_fill
  {static} +dynamic tray_fill
  {static} +dynamic tray_full
  {static} +dynamic tray_full_fill
  {static} +dynamic tree
  {static} +dynamic triangle
  {static} +dynamic triangle_fill
  {static} +dynamic triangle_lefthalf_fill
  {static} +dynamic triangle_righthalf_fill
  {static} +dynamic tropicalstorm
  {static} +dynamic tuningfork
  {static} +dynamic tv
  {static} +dynamic tv_circle
  {static} +dynamic tv_circle_fill
  {static} +dynamic tv_fill
  {static} +dynamic tv_music_note
  {static} +dynamic tv_music_note_fill
  {static} +dynamic uiwindow_split_2x1
  {static} +dynamic umbrella
  {static} +dynamic umbrella_fill
  {static} +dynamic underline
  {static} +dynamic upload_circle
  {static} +dynamic upload_circle_fill
  {static} +dynamic videocam
  {static} +dynamic videocam_circle
  {static} +dynamic videocam_circle_fill
  {static} +dynamic videocam_fill
  {static} +dynamic view_2d
  {static} +dynamic view_3d
  {static} +dynamic viewfinder
  {static} +dynamic viewfinder_circle
  {static} +dynamic viewfinder_circle_fill
  {static} +dynamic wand_rays
  {static} +dynamic wand_rays_inverse
  {static} +dynamic wand_stars
  {static} +dynamic wand_stars_inverse
  {static} +dynamic waveform
  {static} +dynamic waveform_circle
  {static} +dynamic waveform_circle_fill
  {static} +dynamic waveform_path
  {static} +dynamic waveform_path_badge_minus
  {static} +dynamic waveform_path_badge_plus
  {static} +dynamic waveform_path_ecg
  {static} +dynamic wifi
  {static} +dynamic wifi_exclamationmark
  {static} +dynamic wifi_slash
  {static} +dynamic wind
  {static} +dynamic wind_snow
  {static} +dynamic wrench
  {static} +dynamic wrench_fill
  {static} +dynamic xmark
  {static} +dynamic xmark_circle
  {static} +dynamic xmark_circle_fill
  {static} +dynamic xmark_octagon
  {static} +dynamic xmark_octagon_fill
  {static} +dynamic xmark_rectangle
  {static} +dynamic xmark_rectangle_fill
  {static} +dynamic xmark_seal
  {static} +dynamic xmark_seal_fill
  {static} +dynamic xmark_shield
  {static} +dynamic xmark_shield_fill
  {static} +dynamic xmark_square
  {static} +dynamic xmark_square_fill
  {static} +dynamic zoom_in
  {static} +dynamic zoom_out
  {static} +dynamic zzz
}


@enduml