@startuml
set namespaceSeparator ::

class "flutter::lib::src::widgets::navigation_toolbar.dart::NavigationToolbar" {
  {static} +double kMiddleSpacing
  +Widget? leading
  +Widget? middle
  +Widget? trailing
  +bool centerMiddle
  +double middleSpacing
  +Widget build()
}

"flutter::lib::src::widgets::navigation_toolbar.dart::NavigationToolbar" o-- "flutter::lib::src::widgets::framework.dart::Widget"
"flutter::lib::src::widgets::framework.dart::StatelessWidget" <|-- "flutter::lib::src::widgets::navigation_toolbar.dart::NavigationToolbar"

class "flutter::lib::src::widgets::navigation_toolbar.dart::_ToolbarLayout" {
  +bool centerMiddle
  +double middleSpacing
  +dynamic textDirection
  +void performLayout()
  +bool shouldRelayout()
}

class "flutter::lib::src::widgets::navigation_toolbar.dart::_ToolbarSlot" {
  +int index
  {static} +List<_ToolbarSlot> values
  {static} +_ToolbarSlot leading
  {static} +_ToolbarSlot middle
  {static} +_ToolbarSlot trailing
}

"flutter::lib::src::widgets::navigation_toolbar.dart::_ToolbarSlot" o-- "flutter::lib::src::widgets::navigation_toolbar.dart::_ToolbarSlot"
"dart::core::Enum" <|-- "flutter::lib::src::widgets::navigation_toolbar.dart::_ToolbarSlot"


@enduml