@startuml
set namespaceSeparator ::

class "flutter::lib::src::widgets::text_selection_toolbar_layout_delegate.dart::TextSelectionToolbarLayoutDelegate" {
  +dynamic anchorAbove
  +dynamic anchorBelow
  +bool? fitsAbove
  {static} -double _centerOn()
  +dynamic getConstraintsForChild()
  +dynamic getPositionForChild()
  +bool shouldRelayout()
}


@enduml