@startuml
set namespaceSeparator ::

abstract class "flutter::lib::src::animation::tween.dart::Animatable" {
  +T transform()
  +T evaluate()
  +Animation<T> animate()
  +Animatable<T> chain()
}

class "flutter::lib::src::animation::tween.dart::_AnimatedEvaluation" {
  +Animation<double> parent
  -Animatable<T> _evaluatable
  +T value
  +String toString()
  +String toStringDetails()
}

"flutter::lib::src::animation::tween.dart::_AnimatedEvaluation" o-- "flutter::lib::src::animation::animation.dart::Animation<double>"
"flutter::lib::src::animation::tween.dart::_AnimatedEvaluation" o-- "flutter::lib::src::animation::tween.dart::Animatable<T>"
"flutter::lib::src::animation::animation.dart::Animation" <|-- "flutter::lib::src::animation::tween.dart::_AnimatedEvaluation"
"flutter::lib::src::animation::animations.dart::AnimationWithParentMixin" <|-- "flutter::lib::src::animation::tween.dart::_AnimatedEvaluation"

class "flutter::lib::src::animation::tween.dart::_ChainedEvaluation" {
  -Animatable<double> _parent
  -Animatable<T> _evaluatable
  +T transform()
  +String toString()
}

"flutter::lib::src::animation::tween.dart::_ChainedEvaluation" o-- "flutter::lib::src::animation::tween.dart::Animatable<double>"
"flutter::lib::src::animation::tween.dart::_ChainedEvaluation" o-- "flutter::lib::src::animation::tween.dart::Animatable<T>"
"flutter::lib::src::animation::tween.dart::Animatable" <|-- "flutter::lib::src::animation::tween.dart::_ChainedEvaluation"

class "flutter::lib::src::animation::tween.dart::Tween" {
  +T? begin
  +T? end
  +T lerp()
  +T transform()
  +String toString()
}

"flutter::lib::src::animation::tween.dart::Animatable" <|-- "flutter::lib::src::animation::tween.dart::Tween"

class "flutter::lib::src::animation::tween.dart::ReverseTween" {
  +Tween<T> parent
  +T lerp()
}

"flutter::lib::src::animation::tween.dart::ReverseTween" o-- "flutter::lib::src::animation::tween.dart::Tween<T>"
"flutter::lib::src::animation::tween.dart::Tween" <|-- "flutter::lib::src::animation::tween.dart::ReverseTween"

class "flutter::lib::src::animation::tween.dart::ColorTween" {
  +dynamic lerp()
}

"flutter::lib::src::animation::tween.dart::Tween" <|-- "flutter::lib::src::animation::tween.dart::ColorTween"

class "flutter::lib::src::animation::tween.dart::SizeTween" {
  +dynamic lerp()
}

"flutter::lib::src::animation::tween.dart::Tween" <|-- "flutter::lib::src::animation::tween.dart::SizeTween"

class "flutter::lib::src::animation::tween.dart::RectTween" {
  +dynamic lerp()
}

"flutter::lib::src::animation::tween.dart::Tween" <|-- "flutter::lib::src::animation::tween.dart::RectTween"

class "flutter::lib::src::animation::tween.dart::IntTween" {
  +int lerp()
}

"flutter::lib::src::animation::tween.dart::Tween" <|-- "flutter::lib::src::animation::tween.dart::IntTween"

class "flutter::lib::src::animation::tween.dart::StepTween" {
  +int lerp()
}

"flutter::lib::src::animation::tween.dart::Tween" <|-- "flutter::lib::src::animation::tween.dart::StepTween"

class "flutter::lib::src::animation::tween.dart::ConstantTween" {
  +T lerp()
  +String toString()
}

"flutter::lib::src::animation::tween.dart::Tween" <|-- "flutter::lib::src::animation::tween.dart::ConstantTween"

class "flutter::lib::src::animation::tween.dart::CurveTween" {
  +Curve curve
  +double transform()
  +String toString()
}

"flutter::lib::src::animation::tween.dart::CurveTween" o-- "flutter::lib::src::animation::curves.dart::Curve"
"flutter::lib::src::animation::tween.dart::Animatable" <|-- "flutter::lib::src::animation::tween.dart::CurveTween"


@enduml